services:
  full_stack_db:
    image: postgres:latest
    container_name: full_stack_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
    networks:
      - full-stack

  full_stack_back:
    container_name: full_stack_back
    build:
      context: ./api
      target: server
    env_file:
      - .env
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    depends_on:
      full_stack_db:
          condition: service_healthy
    networks:
      - full-stack

  # ! If this name dont contain "full_stack" change on ./client/lib/Constants.ts
  full_stack_front:
    container_name: full_stack_front
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client
    env_file:
      - .env
    environment:
      NODE_ENV: docker
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    networks:
      - full-stack
    depends_on:
      - full_stack_back

networks:
  full-stack:
    driver: bridge